apiVersion: v1
kind: service
metadata:
  name: db
  labels: postgres-service
  app: demo-voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selectors:
    name: postgres-pod
    app: demo-voting-app