apiVersion: v1
kind: service
metadata:
  name: result-service
  labels: result-service
  app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selectors:
    name: result-app-pod
    app: demo-voting-app