apiVersion: v1
kind: Pod
Metadata:
  name: result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app-pod
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - containerPort: 80