apiVersion: v1
kind: service
metadata:
  name: voting-service
  labels: voting-service
  app: demo-voting-app
spec:
  type: nodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selectors:
    name: voting-app-pod
    app: demo-voting-app